apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-hom
spec:
  destination:
    name: ''
    namespace: oqss-hom
    server: 'https://kubernetes.default.svc'
  source:
    path: oqss-hom
    repoURL: 'http://gitea-oqss-cicd.apps.middleware.rhbr-lab.com/gitea-admin/oqss-cnp-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
