apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipeline
spec:
  destination:
    name: ''
    namespace: oqss-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: pipeline/kustomize
    repoURL: 'http://gitea.apps.middleware.rhbr-lab.com/gitea-admin/oqss-cicd-manifests'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
