apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
spec:
  destination:
    name: ''
    namespace: oqss-cicd
    server: 'https://kubernetes.default.svc'
  source:
    path: oqss-cicd/sonarqube/helm
    repoURL: 'http://gitea-oqss-cicd.apps.cluster-jx6jr.jx6jr.sandbox760.opentlc.com/gitea-admin/oqss-cnp-gitops'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
