apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube
spec:
  destination:
    name: ''
    namespace: oqss-testes
    server: 'https://kubernetes.default.svc'
  source:
    path: ci-tools/sonarqube/helm
    repoURL: 'https://github.com/redhat-oraex/oqss-cicd-manifests'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
